[tool.poetry]
name = "quiz-tg-bot"
version = "0.1.0"
description = ""
authors = [
    {name = "Anonimous",email = "Anonimous@mail.ru"}
]

[tool.poetry.dependencies]
python = ">=3.13"
aiogram = ">=3.22.0,<4.0.0"
python-dotenv = ">=1.2.1,<2.0.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"